import type { IntakeFieldDefinition, IntakeStepDefinition } from "@/lib/domain/intakeConfig";

function f(field: IntakeFieldDefinition): IntakeFieldDefinition {
  return field;
}

export const COMMERCIAL_INTAKE_STEP_DEFINITIONS: IntakeStepDefinition[] = [
  {
    key: "commercial_basics",
    title: "The Basics",
    subtitle: "Quick facts about the property and sale context.",
    description: "Capture ownership, sale intent, and transaction setup details.",
    estimatedMinutes: 7,
    helpText: "Phase 1 of 6",
    fields: [
      f({ name: "c1_1_full_address", label: "Q1. Full property address", type: "text", required: true }),
      f({
        name: "c1_2_property_type",
        label: "Q2. Property type",
        type: "single_select",
        required: true,
        options: ["Office", "Retail", "Warehouse", "Industrial", "Mixed-use", "Medical", "Showroom", "Other"],
      }),
      f({ name: "c1_2_property_type_other", label: "Q2. Property type (other)", type: "text", required: true, condition: { field: "c1_2_property_type", equals: "Other" } }),
      f({
        name: "c1_3_sale_structure",
        label: "Q3. What is being sold?",
        type: "single_select",
        required: true,
        options: ["Freehold", "Leasehold interest", "Business + property", "Other"],
      }),
      f({ name: "c1_3_sale_structure_other", label: "Q3. Sale structure details", type: "textarea", condition: { field: "c1_3_sale_structure", equals: "Other" } }),
      f({
        name: "c1_4_occupancy_status",
        label: "Q4. Current occupancy",
        type: "single_select",
        required: true,
        options: ["Tenanted", "Owner-occupied", "Vacant", "Partially occupied"],
      }),
      f({ name: "c1_5_ownership_duration", label: "Q5. How long have you owned it?", type: "text" }),
      f({ name: "c1_6_reason_for_sale", label: "Q6. Why are you selling?", type: "textarea", required: true }),
      f({ name: "c1_7_price_expectation", label: "Q7. Price expectation or guide", type: "currency" }),
      f({ name: "c1_8_sale_timeline", label: "Q8. Ideal timeline to sell", type: "text" }),
      f({
        name: "c1_9_sale_method",
        label: "Q9. Preferred sale method",
        type: "single_select",
        options: ["Private treaty", "Expressions of interest", "Auction", "Off-market", "Open to advice"],
      }),
      f({ name: "c1_10_special_conditions", label: "Q10. Special sale conditions", type: "textarea" }),
      f({ name: "c1_11_decision_makers", label: "Q11. Decision-makers", type: "textarea", required: true }),
      f({
        name: "c1_12_legal_advisor_appointed",
        label: "Q12. Solicitor or conveyancer appointed?",
        type: "single_select",
        required: true,
        options: ["Yes", "No"],
      }),
      f({ name: "c1_13_prior_campaign_history", label: "Q13. Prior market campaign history", type: "textarea" }),
      f({ name: "c1_14_sensitive_handling_notes", label: "Q14. Sensitive handling notes", type: "textarea" }),
    ],
  },
  {
    key: "commercial_property",
    title: "The Property",
    subtitle: "What the buyer is actually walking into.",
    description: "Capture physical profile, constraints, and planning context.",
    estimatedMinutes: 8,
    helpText: "Phase 2 of 6",
    fields: [
      f({ name: "c2_15_land_area", label: "Q15. Total land area", type: "text" }),
      f({ name: "c2_16_building_area", label: "Q16. Total building area", type: "text" }),
      f({ name: "c2_17_age_upgrades", label: "Q17. Building age and major upgrades", type: "textarea" }),
      f({
        name: "c2_18_condition",
        label: "Q18. Current property condition",
        type: "single_select",
        options: ["Excellent", "Good", "Fair", "Needs work"],
      }),
      f({ name: "c2_19_defects_issues", label: "Q19. Known defects or maintenance issues", type: "textarea" }),
      f({ name: "c2_20_services_connected", label: "Q20. Services connected", type: "multi_select", options: ["Single-phase power", "Three-phase power", "Water", "Sewer", "Gas", "NBN", "Stormwater", "Other"] }),
      f({ name: "c2_20_services_connected_other", label: "Q20. Other services", type: "text", condition: { field: "c2_20_services_connected", equals: "Other" } }),
      f({ name: "c2_21_parking_access", label: "Q21. Parking and access", type: "textarea" }),
      f({ name: "c2_22_frontage_visibility", label: "Q22. Street frontage and visibility", type: "textarea" }),
      f({ name: "c2_23_unique_physical_features", label: "Q23. Unique physical features", type: "textarea" }),
      f({ name: "c2_24_zoning", label: "Q24. Current zoning", type: "text" }),
      f({ name: "c2_25_planning_overlays", label: "Q25. Planning overlays or restrictions", type: "textarea" }),
      f({ name: "c2_26_da_history", label: "Q26. Current or lapsed development approvals", type: "textarea" }),
      f({ name: "c2_27_unapproved_works", label: "Q27. Unapproved works or structures", type: "textarea" }),
      f({ name: "c2_28_contamination_history", label: "Q28. Contamination history or environmental concerns", type: "textarea" }),
      f({ name: "c2_29_neighbouring_uses", label: "Q29. Neighbouring property uses", type: "textarea" }),
      f({ name: "c2_30_first_impression", label: "Q30. What would impress a buyer? What would not?", type: "textarea" }),
    ],
  },
  {
    key: "commercial_numbers",
    title: "The Numbers",
    subtitle: "Financial and lease position.",
    description: "Capture rent profile, outgoings, obligations, and pricing anchors.",
    estimatedMinutes: 8,
    helpText: "Phase 3 of 6",
    fields: [
      f({ name: "c3_31_annual_rent", label: "Q31. Current annual rent", type: "currency" }),
      f({ name: "c3_31_rent_basis", label: "Q31. Rent basis", type: "single_select", options: ["Net", "Gross", "Mixed", "N/A"] }),
      f({ name: "c3_32_lease_expiry_options", label: "Q32. Lease expiry and options", type: "textarea" }),
      f({ name: "c3_33_rent_review_structure", label: "Q33. Rent review structure", type: "single_select", options: ["CPI", "Fixed %", "Market review", "Combination", "Other"] }),
      f({ name: "c3_33_rent_review_other", label: "Q33. Rent review structure (other)", type: "text", condition: { field: "c3_33_rent_review_structure", equals: "Other" } }),
      f({ name: "c3_34_arrears_disputes", label: "Q34. Rent arrears/disputes history", type: "textarea" }),
      f({ name: "c3_35_tenant_strength", label: "Q35. Tenant financial strength/stability", type: "textarea" }),
      f({ name: "c3_36_outgoings_split", label: "Q36. Outgoings split (tenant vs landlord)", type: "textarea" }),
      f({ name: "c3_37_council_rates", label: "Q37. Annual council rates", type: "currency" }),
      f({ name: "c3_38_insurance", label: "Q38. Annual insurance cost", type: "currency" }),
      f({ name: "c3_39_land_tax", label: "Q39. Annual land tax", type: "currency" }),
      f({ name: "c3_40_other_owner_costs", label: "Q40. Other regular owner costs", type: "textarea" }),
      f({ name: "c3_41_upcoming_major_capex", label: "Q41. Upcoming major maintenance/capex", type: "textarea" }),
      f({
        name: "c3_42_gst_treatment",
        label: "Q42. GST treatment expectation",
        type: "single_select",
        options: ["Going concern", "Margin scheme", "Standard GST", "Unsure"],
      }),
      f({ name: "c3_43_recent_valuation", label: "Q43. Most recent valuation or rates valuation", type: "currency" }),
      f({
        name: "c3_44_mortgage_debt",
        label: "Q44. Mortgage/debt on property",
        type: "single_select",
        options: ["Yes", "No", "Prefer not to say"],
      }),
      f({ name: "c3_45_recent_appraisal", label: "Q45. Recent valuation/appraisal details", type: "textarea" }),
      f({ name: "c3_46_financial_explanations", label: "Q46. Financial items needing buyer explanation", type: "textarea" }),
    ],
  },
  {
    key: "commercial_area_market",
    title: "The Area & Market",
    subtitle: "Local market context and positioning.",
    description: "Capture demand drivers, comparables, and buyer profile.",
    estimatedMinutes: 7,
    helpText: "Phase 4 of 6",
    fields: [
      f({ name: "c4_47_location_strengths", label: "Q47. Best location strengths", type: "textarea" }),
      f({ name: "c4_48_area_profile", label: "Q48. What the area is known for commercially", type: "textarea" }),
      f({ name: "c4_49_area_change", label: "Q49. Area changes since ownership", type: "textarea" }),
      f({ name: "c4_50_upcoming_infrastructure", label: "Q50. Upcoming nearby projects/developments", type: "textarea" }),
      f({ name: "c4_51_buyer_types", label: "Q51. Likely interested buyer types", type: "textarea", required: true }),
      f({ name: "c4_52_dream_buyer", label: "Q52. Dream buyer and why", type: "textarea" }),
      f({ name: "c4_53_nearby_comparables", label: "Q53. Similar properties sold nearby", type: "textarea" }),
      f({ name: "c4_54_current_competitors", label: "Q54. Competing properties currently for sale", type: "textarea" }),
      f({ name: "c4_55_differentiators", label: "Q55. How this property stands out", type: "textarea" }),
      f({ name: "c4_56_sector_factors", label: "Q56. Sector/industry factors affecting demand", type: "textarea" }),
      f({ name: "c4_57_why_buy", label: "Q57. Why should a buyer purchase this property?", type: "textarea", required: true }),
      f({ name: "c4_58_buyer_hesitation", label: "Q58. Most likely buyer hesitation", type: "textarea" }),
    ],
  },
  {
    key: "commercial_story",
    title: "Your Story",
    subtitle: "Narrative and transferability context.",
    description: "Capture legacy, emotional anchors, and future upside story.",
    estimatedMinutes: 7,
    helpText: "Phase 5 of 6",
    fields: [
      f({ name: "c5_59_why_acquired", label: "Q59. Why was the property originally acquired?", type: "textarea" }),
      f({ name: "c5_60_property_meaning", label: "Q60. What has this property meant to you/business?", type: "textarea" }),
      f({ name: "c5_61_best_moment", label: "Q61. Best moment/milestone here", type: "textarea" }),
      f({ name: "c5_62_if_walls_could_talk", label: "Q62. If the walls could talk", type: "textarea" }),
      f({ name: "c5_63_what_youll_miss", label: "Q63. What will you miss about it?", type: "textarea" }),
      f({ name: "c5_64_unrealised_potential", label: "Q64. Unrealised potential", type: "textarea" }),
      f({ name: "c5_65_best_next_owner", label: "Q65. Who is it ideal for next?", type: "textarea" }),
      f({ name: "c5_66_legacy_reputation", label: "Q66. Legacy or reputation attached to property", type: "textarea" }),
      f({ name: "c5_67_two_sentence_description", label: "Q67. Two-sentence property description", type: "textarea", required: true }),
      f({ name: "c5_68_desired_buyer_feeling", label: "Q68. Desired buyer feeling on inspection", type: "textarea" }),
      f({ name: "c5_69_one_guarantee", label: "Q69. One guarantee to the next owner", type: "textarea" }),
      f({ name: "c5_70_additional_story_notes", label: "Q70. Anything else that matters", type: "textarea" }),
    ],
  },
  {
    key: "commercial_docs_practical",
    title: "Documents & Practical",
    subtitle: "Final documents, access, and logistics.",
    description: "Collect critical documents and practical execution details.",
    estimatedMinutes: 8,
    helpText: "Phase 6 of 6",
    fields: [
      f({ name: "c6_71_title_search", label: "Q71. Upload title search", type: "upload", uploadCategory: "LEGAL", helperText: "Required before final submission." }),
      f({ name: "c6_72_lease_docs", label: "Q72. Upload lease documents", type: "upload", uploadCategory: "LEGAL", helperText: "Required for tenanted assets." }),
      f({ name: "c6_73_council_rates_notice", label: "Q73. Upload council rates notice", type: "upload", uploadCategory: "LEGAL" }),
      f({ name: "c6_74_valuation_docs", label: "Q74. Upload valuation/appraisal documents", type: "upload", uploadCategory: "FINANCIALS" }),
      f({ name: "c6_75_plans_surveys", label: "Q75. Upload plans/surveys/floor plans", type: "upload", uploadCategory: "PROPERTY" }),
      f({ name: "c6_76_approvals_compliance", label: "Q76. Upload approvals/certifications/compliance", type: "upload", uploadCategory: "LEGAL" }),
      f({ name: "c6_77_professional_photos", label: "Q77. Upload professional property photos", type: "upload", uploadCategory: "PROPERTY", helperText: "Minimum 3 files required before final submission." }),
      f({ name: "c6_78_photo_exclusions", label: "Q78. Photos not to use", type: "textarea" }),
      f({
        name: "c6_79_available_for_shoot",
        label: "Q79. Available for professional photo/video shoot?",
        type: "single_select",
        options: ["Yes", "No", "Needs coordination"],
      }),
      f({ name: "c6_80_camera_ready_requirements", label: "Q80. What is needed before camera-ready?", type: "textarea" }),
      f({ name: "c6_81_access_contact", label: "Q81. Main access/logistics contact", type: "textarea", required: true }),
      f({ name: "c6_82_other_supporting_docs", label: "Q82. Upload other supporting documents", type: "upload", uploadCategory: "OTHER" }),
      f({ name: "c6_83_anything_else", label: "Q83. Anything else we should know?", type: "textarea" }),
    ],
  },
];
